services:
    mosquitto-local:
        image: eclipse-mosquitto
        ports:
          - 1883:1883
        volumes:
          - type: bind
            source: ./mosquitto
            target: /mosquitto
